### ISSUE TITLE
Tagging releases

### ISSUE THREAD

**Issue by gslowikowski** [playframework/play-ws#93]
Tag every release, please.

**Comment by schmitch** [comment]
currently this should work now, the first releases were probably untagged since sbt-release was not configured.

**Comment by gslowikowski** [comment]
Can you manually create tags for previous releases?

**Comment by schmitch** [comment]
well I don't know the actual commits, and they were probably just milestones. maybe @wsargent knows them and can do that?

**Comment by marcospereira** [comment]
We still have some configurations to do, see #92.

The tagging step is not working correctly, at least no tag was pushed for M6.

**Comment by wsargent** [comment]
Getting sbt-release to actually work has been non-trivial.  If someone can lend a hand that would be nice...

**Comment by gmethvin** [comment]
So, I did the last release (1.0.0-M6), and it turns out sbt-release created the tag locally but it didn't get pushed to remote. A `git push --tags` fixed that. So this seems like this a possible bug in sbt-release.

**Comment by gslowikowski** [comment]
The last question in release process is "Push changes to the remote repository (y/n)? [y]". If you answer "yes" [pushChanges](https://github.com/sbt/sbt-release/blob/v1.0.3/src/main/scala/ReleaseExtra.scala#L213) step is performed. It calls VCS (Git in this case) [pushChanges](https://github.com/sbt/sbt-release/blob/v1.0.3/src/main/scala/ReleaseExtra.scala#L245) method and it should [push tags](https://github.com/sbt/sbt-release/blob/v1.0.3/src/main/scala/Vcs.scala#L139).

BTW I always answer "no" to the question and push changes manually after successful release (when I see new artifacts in Maven central repo).

**Comment by marcospereira** [comment]
@wsargent was this fixed by #106 and #107?

**Comment by wsargent** [comment]
Yes 😄
